services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rush_order
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rush_order
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # 로컬의 mysql-data를 컨테이너 내부 /var/lib/mysql에 마운트
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--bind-address=0.0.0.0'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:    # 볼륨 정의 확인
