spring:
  profiles:
    active: local  # 기본 활성화 프로파일 설정 (local, docker, test 중 하나 선택)

---

# 1. 로컬 개발 환경 - MySQL
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rushorder82@gmail.com
    password: jekq kvui acez exgs
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  config:
    activate:
      on-profile: local  # local 프로파일 활성화 시 적용

  datasource:
    url: jdbc:mysql://db:3306/rushorder
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 컨테이너 환경에서도 자동 업데이트 사용
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret:
    key: "7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg=="
  token:
    expiration:
      access-token: 3600000  # 1시간 (밀리초 단위)
      refresh-token: 86400000 # 24시간 (밀리초 단위)
  algorithm: HS256  # 사용할 JWT 서명 알고리즘 (예: HS256)

---



---
# 3. 테스트 환경 - H2 Database
spring:
  config:
    activate:
      on-profile: test  # test 프로파일 활성화 시 적용
  datasource:
    url: jdbc:h2:mem:testdb  # 메모리 상의 H2 데이터베이스
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트 후 테이블 자동 삭제
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
